# name: Trigger Target Workflow

# on:
#   push:
#     branches:
#       - main  # Trigger when there is a push to the main branch

# jobs:
#   trigger:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Trigger Workflow in Another Repository
#         run: |
#           repo_owner="simehta7"
#           repo_name="repo2"
#           event_type="update_workflows"

#           curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.MY_TOKEN}}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
#             -d "{\"event_type\": \"$event_type\"}"


name: Trigger Dispatch

on:
  push:
    paths:
      - '**.yml'  # Trigger on changes to any YAML file in the repository

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository dispatch
        run: |
          repo_owner="simehta7"  # Replace with your organization or username
          repo_name="repo2"                           # Replace with your target repository name
          event_type="update_workflows"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
