# # # # central-workflows/.github/workflows/dispatch.yml
# # # name: Dispatch Workflow

# # # on:
# # #   push:
# # #     branches:
# # #       - main  # Trigger on push to main branchh

# # # jobs:
# # #   dispatch:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - name: Trigger repository dispatch
# # #         env:
# # #           REPO: qb2test  # Replace with the actual repository name
# # #         run: |
# # #           curl -X POST \
# # #             -H "Accept: application/vnd.github.v3+json" \
# # #             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
# # #             https://api.github.com/repos/American-Institutes-for-Research/qb2test/dispatches \
# # #             -d '{"event_type":"update_workflows"}'


# # # central-workflows/.github/workflows/dispatch.yml
# # # central-workflows/.github/workflows/dispatch.yml
# # # name: Dispatch Workflow

# # # on:
# # #   push:
# # #     branches:
# # #       - main  # Trigger on push to the main branch

# # # permissions:
# # #   contents: write
# # #   actions: write  # Ensure GITHUB_TOKEN has write access to contents

# # # jobs:
# # #   dispatch:
# # #     runs-on: ubuntu-latest
# # #     steps:
# # #       - name: Trigger repository dispatch
# # #         env:
# # #           REPO: qb2test  # Replace with the actual repository name
# # #           OWNER: American-Institutes-for-Research  # Replace with the actual owner name
# # #         run: |
# # #           curl -X POST \
# # #             -H "Accept: application/vnd.github.v3+json" \
# # #             -H "Authorization: token ${{ secrets.GGITHUB_TOKEN }}" \
# # #             https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
# # #             -d '{"event_type":"update_workflows"}'


# # # central-workflows/.github/workflows/dispatch.yml
# # name: Dispatch Workflow

# # on:
# #   push:
# #     branches:
# #       - main  # Trigger on push to the main branch

# # jobs:
# #   dispatch:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Trigger repository dispatch
# #         env:
# #           REPO: qb2test  # Replace with the actual repository name
# #           OWNER: American-Institutes-for-Research  # Replace with the actual owner name
# #           TOKEN: ${{ secrets.GGITHUB_TOKEN }}
# #         run: |
# #           curl -X POST \
# #             -H "Accept: application/vnd.github.v3+json" \
# #             -H "Authorization: token $TOKEN" \
# #             https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
# #             -d '{"event_type":"update_workflows"}'

# # central-workflows/.github/workflows/dispatch.yml
# name: Dispatch Workflow

# on:
#   push:
#     branches:
#       - main  # Trigger on push to the main branch

# permissions:
#   contents: write  # Ensure GITHUB_TOKEN has write access to contents
#   actions: write   # Ensure GITHUB_TOKEN has write access to workflows

# jobs:
#   dispatch:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger repository dispatch
#         env:
#           REPO: qb2test  # Replace with the actual repository name
#           OWNER: American-Institutes-for-Research  # Replace with the actual owner name
#           TOKEN: ${{ secrets.MY_PAT }}
#         run: |
#           curl -X POST \
#             -H "Accept: application/vnd.github.v3+json" \
#             -H "Authorization: token $TOKEN" \
#             https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
#             -d '{"event_type":"update_workflows"}'


name: Trigger Target Workflow

on:
  push:
    branches:
      - main  # Trigger when there is a push to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          repo_owner="American-Institutes-for-Research"
          repo_name="repo2"
          event_type="update_workflows"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
